// AUTO-GENERATED by scripts/ingest-assets.mjs — do not edit by hand.
export type Media = { slug: string; file: string; src: string };

export const POSTER_FILES: Media[] = [
  {
    "slug": "abstract-wave-floating-in-void",
    "file": "/posters/abstract-wave-floating-in-void.jpg",
    "src": "Abstract_wave_floating_in_void_2K_202609031714.jpeg"
  },
  {
    "slug": "architectural-hallway-between-de",
    "file": "/posters/architectural-hallway-between-de.jpg",
    "src": "Architectural_hallway_between_de…_2K_202609031715.jpeg"
  },
  {
    "slug": "astronaut-viewing-planet-poster",
    "file": "/posters/astronaut-viewing-planet-poster.jpg",
    "src": "Astronaut_viewing_planet_poster_2K_202609031715.jpeg"
  },
  {
    "slug": "brutalist-architecture-poster-vo",
    "file": "/posters/brutalist-architecture-poster-vo.jpg",
    "src": "Brutalist_architecture_poster_vo…_2K_202609031715.jpeg"
  },
  {
    "slug": "collage-showing-404-error-doorway",
    "file": "/posters/collage-showing-404-error-doorway.jpg",
    "src": "Collage_showing_404_error_doorway_2K_202609031715.jpeg"
  },
  {
    "slug": "electronic-music-poster-afterlight",
    "file": "/posters/electronic-music-poster-afterlight.jpg",
    "src": "Electronic_music_poster_AFTERLIGHT_2K_202609031718.jpeg"
  },
  {
    "slug": "film-camera-photography-exhibiti",
    "file": "/posters/film-camera-photography-exhibiti.jpg",
    "src": "Film_camera_photography_exhibiti…_2K_202609031715.jpeg"
  },
  {
    "slug": "floating-futuristic-city-above-o",
    "file": "/posters/floating-futuristic-city-above-o.jpg",
    "src": "Floating_futuristic_city_above_o…_2K_202609031715.jpeg"
  },
  {
    "slug": "futuristic-archaeology-poster-sh",
    "file": "/posters/futuristic-archaeology-poster-sh.jpg",
    "src": "Futuristic_archaeology_poster_sh…_2K_202609031715.jpeg"
  },
  {
    "slug": "giant-eye-floating-above-city",
    "file": "/posters/giant-eye-floating-above-city.jpg",
    "src": "Giant_eye_floating_above_city_2K_202609031715.jpeg"
  },
  {
    "slug": "glass-archival-drawer-with-dream",
    "file": "/posters/glass-archival-drawer-with-dream.jpg",
    "src": "Glass_archival_drawer_with_dream…_2K_202609031715.jpeg"
  },
  {
    "slug": "glass-flower-botanical-poster",
    "file": "/posters/glass-flower-botanical-poster.jpg",
    "src": "Glass_flower_botanical_poster_2K_202609031715.jpeg"
  },
  {
    "slug": "human-hand-touching-artificial-hand",
    "file": "/posters/human-hand-touching-artificial-hand.jpg",
    "src": "Human_hand_touching_artificial_hand_2K_202609031716.jpeg"
  },
  {
    "slug": "impossible-flower-growing-from-s",
    "file": "/posters/impossible-flower-growing-from-s.jpg",
    "src": "Impossible_flower_growing_from_s…_2K_202609031715.jpeg"
  },
  {
    "slug": "light-bending-stone-platform",
    "file": "/posters/light-bending-stone-platform.jpg",
    "src": "Light_bending_stone_platform_2K_202609031715.jpeg"
  },
  {
    "slug": "marble-sculpture-fragmenting-int",
    "file": "/posters/marble-sculpture-fragmenting-int.jpg",
    "src": "Marble_sculpture_fragmenting_int…_2K_202609031715.jpeg"
  },
  {
    "slug": "minimalist-art-poster-the-unseen",
    "file": "/posters/minimalist-art-poster-the-unseen.jpg",
    "src": "Minimalist_art_poster_THE_UNSEEN_2K_202609031715.jpeg"
  },
  {
    "slug": "monolith-on-prehistoric-earth",
    "file": "/posters/monolith-on-prehistoric-earth.jpg",
    "src": "Monolith_on_prehistoric_Earth_2K_202609031714.jpeg"
  },
  {
    "slug": "parallel-city-architectural-post",
    "file": "/posters/parallel-city-architectural-post.jpg",
    "src": "Parallel_city_architectural_post…_2K_202609031714.jpeg"
  },
  {
    "slug": "parallel-city-design-festival-po",
    "file": "/posters/parallel-city-design-festival-po.jpg",
    "src": "Parallel_City_design_festival_po…_2K_202609031716.jpeg"
  },
  {
    "slug": "retro-radio-concert-poster",
    "file": "/posters/retro-radio-concert-poster.jpg",
    "src": "Retro_radio_concert_poster_2K_202609031717.jpeg"
  },
  {
    "slug": "sculpted-hand-floating-paper-fra",
    "file": "/posters/sculpted-hand-floating-paper-fra.jpg",
    "src": "Sculpted_hand_floating_paper_fra…_2K_202609031714.jpeg"
  },
  {
    "slug": "statue-standing-in-flood-water",
    "file": "/posters/statue-standing-in-flood-water.jpg",
    "src": "Statue_standing_in_flood_water_2K_202609031716.jpeg"
  },
  {
    "slug": "surreal-desert-landscape-art-poster",
    "file": "/posters/surreal-desert-landscape-art-poster.jpg",
    "src": "Surreal_desert_landscape_art_poster_2K_202609031716.jpeg"
  },
  {
    "slug": "synesthesia-visual-music-poster",
    "file": "/posters/synesthesia-visual-music-poster.jpg",
    "src": "Synesthesia_visual_music_poster_…_2K_202609031715.jpeg"
  }
];
export const SOCIAL_FILES: Media[] = [
  {
    "slug": "auren-botanical-absence-study-co",
    "file": "/social/auren-botanical-absence-study-co.jpg",
    "src": "AUREN_botanical_absence_study_co…_2K_202609032257.jpeg"
  },
  {
    "slug": "auren-botanical-study-ad-design",
    "file": "/social/auren-botanical-study-ad-design.jpg",
    "src": "Auren_botanical_study_ad_design_2K_202609032258.jpeg"
  },
  {
    "slug": "auren-botanical-x-ray-design",
    "file": "/social/auren-botanical-x-ray-design.jpg",
    "src": "AUREN_botanical_X-ray_design_2K_202609032258.jpeg"
  },
  {
    "slug": "auren-bottle-membrane-concept",
    "file": "/social/auren-bottle-membrane-concept.jpg",
    "src": "Auren_bottle_membrane_concept_2K_202609032257.jpeg"
  },
  {
    "slug": "auren-brand-logo-design",
    "file": "/social/auren-brand-logo-design.png",
    "src": "AUREN_brand_logo_design_2K_202609040020-Photoroom.png"
  },
  {
    "slug": "botanical-skin-clock-design",
    "file": "/social/botanical-skin-clock-design.jpg",
    "src": "Botanical_skin_clock_design_2K_202609032257.jpeg"
  },
  {
    "slug": "coffee-map-creative-direction-de",
    "file": "/social/coffee-map-creative-direction-de.jpg",
    "src": "Coffee_map_creative_direction_de…_2K_202609032258.jpeg"
  },
  {
    "slug": "continuous-table-passing-through",
    "file": "/social/continuous-table-passing-through.jpg",
    "src": "Continuous_table_passing_through…_2K_202609032256.jpeg"
  },
  {
    "slug": "designing-auren-formula-landscap",
    "file": "/social/designing-auren-formula-landscap.jpg",
    "src": "Designing_AUREN_formula_landscap…_2K_202609032257.jpeg"
  },
  {
    "slug": "designing-luxury-hotel-room-adve",
    "file": "/social/designing-luxury-hotel-room-adve.jpg",
    "src": "Designing_luxury_hotel_room_adve…_2K_202609032257.jpeg"
  },
  {
    "slug": "detective-investigates-coffee-sp",
    "file": "/social/detective-investigates-coffee-sp.jpg",
    "src": "Detective_investigates_coffee_sp…_2K_202609032258.jpeg"
  },
  {
    "slug": "espresso-drop-containing-microsc",
    "file": "/social/espresso-drop-containing-microsc.jpg",
    "src": "Espresso_drop_containing_microsc…_2K_202609032257.jpeg"
  },
  {
    "slug": "floating-hotel-door-in-space",
    "file": "/social/floating-hotel-door-in-space.jpg",
    "src": "Floating_hotel_door_in_space_2K_202609032257.jpeg"
  },
  {
    "slug": "giant-shoe-in-city",
    "file": "/social/giant-shoe-in-city.jpg",
    "src": "Giant_shoe_in_city_2K_202609032257.jpeg"
  },
  {
    "slug": "koro-architectural-coffee-cup-co",
    "file": "/social/koro-architectural-coffee-cup-co.jpg",
    "src": "KORO_architectural_coffee_cup_co…_2K_202609032257.jpeg"
  },
  {
    "slug": "koro-brand-logo-display",
    "file": "/social/koro-brand-logo-display.png",
    "src": "KORO_brand_logo_display_2K_202609032325-Photoroom.png"
  },
  {
    "slug": "koro-coffee-machine-design-concept",
    "file": "/social/koro-coffee-machine-design-concept.jpg",
    "src": "KORO_coffee_machine_design_concept_2K_202609032257.jpeg"
  },
  {
    "slug": "orbital-house-brand-logo",
    "file": "/social/orbital-house-brand-logo.png",
    "src": "Orbital_House_brand_logo_2K_202609040020-Photoroom.png"
  },
  {
    "slug": "orbital-house-hotel-check-in-con",
    "file": "/social/orbital-house-hotel-check-in-con.jpg",
    "src": "Orbital_House_hotel_check-in_con…_2K_202609032257.jpeg"
  },
  {
    "slug": "orbital-house-pool-concept-design",
    "file": "/social/orbital-house-pool-concept-design.jpg",
    "src": "Orbital_House_pool_concept_design_2K_202609032257.jpeg"
  },
  {
    "slug": "orbital-house-rotating-hotel-con",
    "file": "/social/orbital-house-rotating-hotel-con.jpg",
    "src": "Orbital_House_rotating_hotel_con…_2K_202609032257.jpeg"
  },
  {
    "slug": "shoe-breaking-architectural-grid",
    "file": "/social/shoe-breaking-architectural-grid.jpg",
    "src": "Shoe_breaking_architectural_grid_2K_202609032257.jpeg"
  },
  {
    "slug": "silver-elevator-in-desert-night",
    "file": "/social/silver-elevator-in-desert-night.png",
    "src": "gemini-clear-Silver_elevator_in_desert_night_2K_202609032258.png"
  },
  {
    "slug": "velora-03-motion-study-design",
    "file": "/social/velora-03-motion-study-design.jpg",
    "src": "VELORA_03_motion_study_design_2K_202609032257.jpeg"
  },
  {
    "slug": "velora-brand-logo-design",
    "file": "/social/velora-brand-logo-design.png",
    "src": "VELORA_brand_logo_design_2K_202609040020-Photoroom.png"
  },
  {
    "slug": "velora-shoe-floating-in-gallery",
    "file": "/social/velora-shoe-floating-in-gallery.jpg",
    "src": "VELORA_shoe_floating_in_gallery_2K_202609032256.jpeg"
  },
  {
    "slug": "velora-shoe-on-moving-floor",
    "file": "/social/velora-shoe-on-moving-floor.jpg",
    "src": "Velora_shoe_on_moving_floor_2K_202609032257.jpeg"
  },
  {
    "slug": "velora-shoe-poster-design-concept",
    "file": "/social/velora-shoe-poster-design-concept.jpg",
    "src": "VELORA_shoe_poster_design_concept_2K_202609032256.jpeg"
  }
];
export const THUMB_FILES: Media[] = [
  {
    "slug": "architecture-thumbnail-design",
    "file": "/thumbnails/architecture-thumbnail-design.jpg",
    "src": "Architecture_thumbnail_design_2K_202609040057.jpeg"
  },
  {
    "slug": "character-surviving-with-1-hp",
    "file": "/thumbnails/character-surviving-with-1-hp.jpg",
    "src": "Character_surviving_with_1_HP_2K_202609040057.jpeg"
  },
  {
    "slug": "cricket-batter-hitting-last-ball",
    "file": "/thumbnails/cricket-batter-hitting-last-ball.jpg",
    "src": "Cricket_batter_hitting_last_ball_2K_202609040057.jpeg"
  },
  {
    "slug": "designing-expensive-coffee-youtu",
    "file": "/thumbnails/designing-expensive-coffee-youtu.jpg",
    "src": "Designing_expensive_coffee_YouTu…_2K_202609040057.jpeg"
  },
  {
    "slug": "football-player-striking-ball",
    "file": "/thumbnails/football-player-striking-ball.jpg",
    "src": "Football_player_striking_ball_2K_202609040058.jpeg"
  }
];
export const ILLO_FILES: Media[] = [
  {
    "slug": "anthropomorphic-fish-chef-holdin",
    "file": "/illustration/anthropomorphic-fish-chef-holdin.png",
    "src": "Anthropomorphic_fish_chef_holdin…_2K_202609040114-Photoroom.png"
  },
  {
    "slug": "apple-princess-in-fashion-pose",
    "file": "/illustration/apple-princess-in-fashion-pose.png",
    "src": "Apple_princess_in_fashion_pose_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "baker-holding-large-rolling-pin",
    "file": "/illustration/baker-holding-large-rolling-pin.png",
    "src": "Baker_holding_large_rolling_pin_2K_202609040122-Photoroom.png"
  },
  {
    "slug": "bird-man-leaning-forward",
    "file": "/illustration/bird-man-leaning-forward.png",
    "src": "Bird_man_leaning_forward_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "chaotic-artist-girl-holding-pain",
    "file": "/illustration/chaotic-artist-girl-holding-pain.png",
    "src": "Chaotic_artist_girl_holding_pain…_2K_202609040114-Photoroom.png"
  },
  {
    "slug": "citrus-woman-fashion-illustration",
    "file": "/illustration/citrus-woman-fashion-illustration.png",
    "src": "Citrus_woman_fashion_illustration_2K_202609040122-Photoroom.png"
  },
  {
    "slug": "elderly-monk-holding-cake-server",
    "file": "/illustration/elderly-monk-holding-cake-server.png",
    "src": "Elderly_monk_holding_cake_server_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "elegant-cake-lady-posing",
    "file": "/illustration/elegant-cake-lady-posing.png",
    "src": "Elegant_cake_lady_posing_2K_202609040114-Photoroom.png"
  },
  {
    "slug": "fashion-girl-standing-confidently",
    "file": "/illustration/fashion-girl-standing-confidently.png",
    "src": "Fashion_girl_standing_confidently_2K_202609040115-Photoroom.png"
  },
  {
    "slug": "fisherman-carrying-net-drawing",
    "file": "/illustration/fisherman-carrying-net-drawing.png",
    "src": "Fisherman_carrying_net_drawing_2K_202609040120-Photoroom.png"
  },
  {
    "slug": "lemon-woman-posing-in-couture",
    "file": "/illustration/lemon-woman-posing-in-couture.png",
    "src": "Lemon_woman_posing_in_couture_2K_202609040115-Photoroom.png"
  },
  {
    "slug": "man-holding-bag-strap",
    "file": "/illustration/man-holding-bag-strap.png",
    "src": "Man_holding_bag_strap_2K_202609040114-Photoroom.png"
  },
  {
    "slug": "man-holding-document-folder",
    "file": "/illustration/man-holding-document-folder.png",
    "src": "Man_holding_document_folder_2K_202609040115-Photoroom.png"
  },
  {
    "slug": "man-holding-fork-illustration",
    "file": "/illustration/man-holding-fork-illustration.png",
    "src": "Man_holding_fork_illustration_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "man-holding-spoon-and-newspaper",
    "file": "/illustration/man-holding-spoon-and-newspaper.png",
    "src": "Man_holding_spoon_and_newspaper_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "man-wearing-architectural-coat",
    "file": "/illustration/man-wearing-architectural-coat.png",
    "src": "Man_wearing_architectural_coat_2K_202609040122-Photoroom.png"
  },
  {
    "slug": "muscular-butcher-holding-cleaver",
    "file": "/illustration/muscular-butcher-holding-cleaver.png",
    "src": "Muscular_butcher_holding_cleaver_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "pasta-woman-fashion-illustration",
    "file": "/illustration/pasta-woman-fashion-illustration.png",
    "src": "Pasta_woman_fashion_illustration…_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "pizza-slice-standing-confidently",
    "file": "/illustration/pizza-slice-standing-confidently.png",
    "src": "Pizza_slice_standing_confidently_2K_202609040114-Photoroom.png"
  },
  {
    "slug": "retired-boxer-in-relaxed-stance",
    "file": "/illustration/retired-boxer-in-relaxed-stance.png",
    "src": "Retired_boxer_in_relaxed_stance_2K_202609040115-Photoroom.png"
  },
  {
    "slug": "stylish-man-in-black-suit",
    "file": "/illustration/stylish-man-in-black-suit.png",
    "src": "Stylish_man_in_black_suit_2K_202609040131-Photoroom.png"
  },
  {
    "slug": "woman-holding-motorcycle-helmet",
    "file": "/illustration/woman-holding-motorcycle-helmet.png",
    "src": "Woman_holding_motorcycle_helmet_2K_202609040131-Photoroom.png"
  },
  {
    "slug": "woman-in-red-dress-illustration",
    "file": "/illustration/woman-in-red-dress-illustration.png",
    "src": "Woman_in_red_dress_illustration_2K_202609040131-Photoroom.png"
  },
  {
    "slug": "woman-wearing-mask-coat",
    "file": "/illustration/woman-wearing-mask-coat.png",
    "src": "Woman_wearing_mask_coat_2K_202609040121-Photoroom.png"
  },
  {
    "slug": "young-woman-walking-forward-illu",
    "file": "/illustration/young-woman-walking-forward-illu.png",
    "src": "Young_woman_walking_forward_illu…_2K_202609040122-Photoroom.png"
  }
];
export const MOTION_FILES: Media[] = [
  {
    "slug": "2d-video-1",
    "file": "/motion/2d-video-1.mp4",
    "src": "2D Video 1.mp4"
  },
  {
    "slug": "2d-video-2",
    "file": "/motion/2d-video-2.mp4",
    "src": "2d video 2.mp4"
  },
  {
    "slug": "2d-video-3",
    "file": "/motion/2d-video-3.mp4",
    "src": "2d video 3.mp4"
  },
  {
    "slug": "2d-video-4",
    "file": "/motion/2d-video-4.mp4",
    "src": "2d video 4.mp4"
  },
  {
    "slug": "3d-video-1",
    "file": "/motion/3d-video-1.mp4",
    "src": "3D Video 1.mp4"
  },
  {
    "slug": "3d-video-2",
    "file": "/motion/3d-video-2.mp4",
    "src": "3d video 2.mp4"
  },
  {
    "slug": "3d-video-3",
    "file": "/motion/3d-video-3.mp4",
    "src": "3d video 3.mp4"
  }
];
export const BRAND_FILES: Media[] = [
  {
    "slug": "auria-brand-visualization",
    "file": "/brands/auria-brand-visualization.jpg",
    "src": "Auria Brand Visualization.jpeg"
  },
  {
    "slug": "auria-sketch",
    "file": "/brands/auria-sketch.jpg",
    "src": "Auria sketch.jpeg"
  },
  {
    "slug": "nexora-brand-visualisation",
    "file": "/brands/nexora-brand-visualisation.jpg",
    "src": "Nexora brand visualisation.jpeg"
  },
  {
    "slug": "nexora-sketch",
    "file": "/brands/nexora-sketch.jpg",
    "src": "nexora sketch.jpeg"
  },
  {
    "slug": "terralis-brand-visualisation",
    "file": "/brands/terralis-brand-visualisation.jpg",
    "src": "terralis brand visualisation.jpeg"
  },
  {
    "slug": "terralis-sketch",
    "file": "/brands/terralis-sketch.jpg",
    "src": "Terralis sketch.jpeg"
  },
  {
    "slug": "vayora-brand-visualisation",
    "file": "/brands/vayora-brand-visualisation.jpg",
    "src": "vayora brand visualisation.jpeg"
  },
  {
    "slug": "vayora-sketch",
    "file": "/brands/vayora-sketch.jpg",
    "src": "Vayora sketch.jpeg"
  },
  {
    "slug": "verdant-brand-visulaisation",
    "file": "/brands/verdant-brand-visulaisation.jpg",
    "src": "Verdant Brand visulaisation.jpeg"
  },
  {
    "slug": "verdant-sketch",
    "file": "/brands/verdant-sketch.jpg",
    "src": "Verdant sketch.jpeg"
  }
];
