/** Galleries. Image lists come from lib/media.ts (generated by scripts/ingest-assets.mjs). */
import { POSTER_FILES, SOCIAL_FILES, THUMB_FILES, ILLO_FILES, MOTION_FILES, type Media } from "./media";

export type Piece = { slug: string; file: string; title: string };

const titleFrom = (slug: string) =>
  slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

const toPieces = (m: Media[], titles: Record<string, string> = {}): Piece[] =>
  m.map((x) => ({ slug: x.slug, file: x.file, title: titles[x.slug] ?? titleFrom(x.slug) }));

export const POSTERS = toPieces(POSTER_FILES, {
  "collage-showing-404-error-doorway": "404 / Between",
  "brutalist-architecture-poster-vo": "City",
  "electronic-music-poster-afterlight": "Afterlight",
  "retro-radio-concert-poster": "On Air",
  "film-camera-photography-exhibiti": "Exposure",
  "giant-eye-floating-above-city": "The Watch",
  "astronaut-viewing-planet-poster": "Distant",
  "surreal-desert-landscape-art-poster": "High Frequency",
  "synesthesia-visual-music-poster": "Synesthesia",
  "marble-sculpture-fragmenting-int": "Fragment",
  "human-hand-touching-artificial-hand": "Contact",
  "statue-standing-in-flood-water": "Flood",
  "monolith-on-prehistoric-earth": "Monolith",
  "floating-futuristic-city-above-o": "Above",
  "abstract-wave-floating-in-void": "Wave",
  "minimalist-art-poster-the-unseen": "The Unseen",
});

// dropped: read as too obviously AI-generated for the archive
const SOCIAL_EXCLUDE = new Set(["continuous-table-passing-through", "koro-coffee-machine-design-concept"]);
export const SOCIAL = toPieces(SOCIAL_FILES.filter((m) => !SOCIAL_EXCLUDE.has(m.slug)));
export const THUMBS = toPieces(THUMB_FILES);
export const ILLOS = toPieces(ILLO_FILES);
export const MOTION = MOTION_FILES.map((m) => ({ slug: m.slug, file: m.file, title: titleFrom(m.slug) }));

export type Brand = {
  slug: string; name: string; tagline: string; sector: string;
  color: string; palette: string[]; board: string; sketch: string; blurb: string;
};

export const BRANDS: Brand[] = [
  {
    slug: "auria", name: "Auria", tagline: "Feel every frequency", sector: "Sound experiences",
    color: "#7c3aed",
    board: "/brands/auria-brand-visualization.jpg", sketch: "/brands/auria-sketch.jpg",
    palette: ["#7c3aed", "#3b1e8f", "#b39cff", "#141416", "#ececea"],
    blurb: "A studio identity for immersive audio. The mark is a live equaliser frozen mid-beat — it reads as sound before it reads as a letter. A violet-to-black system that carries from app UI to retail signage and merch.",
  },
  {
    slug: "nexora", name: "Nexora", tagline: "Beyond the ordinary", sector: "Property / architecture",
    color: "#ffd400",
    board: "/brands/nexora-brand-visualisation.jpg", sketch: "/brands/nexora-sketch.jpg",
    palette: ["#ffd400", "#c88a1f", "#2a2318", "#0a0a0b", "#e8e2d4"],
    blurb: "A property brand built on an arch and a rising stair — climb, threshold, the ordinary left behind. Gold on matte black across stationery, vehicle livery, hoardings and the pitch deck.",
  },
  {
    slug: "terralis", name: "Terralis", tagline: "Earth. Craft. Home.", sector: "Homeware",
    color: "#b98a4b",
    board: "/brands/terralis-brand-visualisation.jpg", sketch: "/brands/terralis-sketch.jpg",
    palette: ["#b98a4b", "#7a8b5a", "#d8c9a3", "#3a3226", "#efe6d2"],
    blurb: "Homeware made by hand. A leaf inside an arched doorway, drawn with one weight so it stamps cleanly on a candle jar or a shipping box. Packaging that looks made, not printed.",
  },
  {
    slug: "vayora", name: "Vayora", tagline: "Quicken forward", sector: "Technology",
    color: "#ff2d1a",
    board: "/brands/vayora-brand-visualisation.jpg", sketch: "/brands/vayora-sketch.jpg",
    palette: ["#ff2d1a", "#0f5c8f", "#1c6b5a", "#0a0a0b", "#e4ecef"],
    blurb: "A tech mark with a hidden V and a star of forward motion. Geometric, minimal, one accent colour. Built to survive a favicon and a billboard without losing the point.",
  },
  {
    slug: "verdant", name: "Verdant", tagline: "Technology that grows a better world", sector: "Plant-tech",
    color: "#2ec27e",
    board: "/brands/verdant-brand-visulaisation.jpg", sketch: "/brands/verdant-sketch.jpg",
    palette: ["#2ec27e", "#1c7a4f", "#a7e3c4", "#12211a", "#eef6f1"],
    blurb: "Plant-tech that grows a better world. Two leaves resolve into a V. Green-forward, applied across app dashboards, environment graphics and merch.",
  },
];
