// Pull every real asset from the user's desktop folders into /public with clean
// slugs, and emit lib/media.ts (the manifest every gallery page reads).
// Run: node scripts/ingest-assets.mjs
import { cp, mkdir, readdir, writeFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, extname, basename } from "node:path";

const DESK = "C:/Users/Ameen/OneDrive/Desktop";
const ROOT = join(process.cwd());
const PUB = join(ROOT, "public");

const slug = (f) =>
  basename(f, extname(f))
    .replace(/gemini[-_]clear[-_]/i, "")
    .replace(/[-_ ]?photoroom(\s*\(\d+\))?$/i, "")
    .replace(/[-_ ]?2k[-_ ]?20\d{10,}$/i, "")
    .replace(/[-_ ]?20\d{10,}$/i, "")
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .replace(/-+/g, "-")
    .slice(0, 60)
    .replace(/-+$/g, "");

/** copy a folder's files (filtered by ext) into public/<dest> as <slug><ext-normalised> */
async function pull(srcDir, dest, exts, rename = {}) {
  const from = join(DESK, srcDir);
  if (!existsSync(from)) { console.warn("MISSING", from); return []; }
  const to = join(PUB, dest);
  await mkdir(to, { recursive: true });
  const out = [];
  for (const name of await readdir(from)) {
    const ext = extname(name).toLowerCase();
    if (!exts.includes(ext)) continue;
    const s = rename[name] ?? slug(name);
    const outExt = ext === ".jpeg" ? ".jpg" : ext;
    await cp(join(from, name), join(to, s + outExt), { force: true });
    out.push({ slug: s, file: `/${dest}/${s}${outExt}`, src: name });
  }
  out.sort((a, b) => a.slug.localeCompare(b.slug));
  console.log(dest.padEnd(14), out.length, "files");
  return out;
}

const IMG = [".jpg", ".jpeg", ".png", ".webp"];
const VID = [".mp4", ".webm", ".mov"];

const posters = await pull("Postars portfolio", "posters", IMG);
const social = await pull("social media posts portfolio", "social", IMG);
const thumbs = await pull("Youtube thumb nails", "thumbnails", IMG);
const illos = await pull("Illustrations Portfolio", "illustration", IMG);
const motion = await pull("2d and 3d portfolio", "motion", VID);
const brands = await pull("brands portfolio", "brands", IMG);

// pixel avatars — already Photoroom cut-outs (transparent)
await pull("Ameen front side back profile", "me", [".png"], {
  "Pixel_character_in_racing_jacket_202609030207-Photoroom.png": "front",
  "Man_side_profile_pixel_art_202609030124-Photoroom (1).png": "side",
  "Character_sprite_back_view_racin…_202609030207-Photoroom.png": "back",
});

// tool icons + zayka monogram
await pull("Assets", "tools", [".png"], {});
if (existsSync(join(DESK, "Assets/zayka_monogram.png")))
  await cp(join(DESK, "Assets/zayka_monogram.png"), join(PUB, "logos/zayka.png"), { force: true });

const manifest = `// AUTO-GENERATED by scripts/ingest-assets.mjs — do not edit by hand.
export type Media = { slug: string; file: string; src: string };

export const POSTER_FILES: Media[] = ${JSON.stringify(posters, null, 2)};
export const SOCIAL_FILES: Media[] = ${JSON.stringify(social, null, 2)};
export const THUMB_FILES: Media[] = ${JSON.stringify(thumbs, null, 2)};
export const ILLO_FILES: Media[] = ${JSON.stringify(illos, null, 2)};
export const MOTION_FILES: Media[] = ${JSON.stringify(motion, null, 2)};
export const BRAND_FILES: Media[] = ${JSON.stringify(brands, null, 2)};
`;
await writeFile(join(ROOT, "lib", "media.ts"), manifest);
console.log("\nlib/media.ts written");
